INSERT INTO Articulos(Autor,FechaCreacion,Titulo,Estado)
VALUES ('Arellano-Verdejo, J., & Alba, E.','5 de marzo de 2016','Optimal allocation of public parking slots using evolutionary Algorithms','Recibido'),
('Arjona, J., Linares, M. P., & Casanovas, J.','3 de octrubre de 2019','A deep learning approach to real-time parking availability prediction for smart cities','Recibido'),
('Aydin, I., Karakose, M., & Karakose, E.','8 de mayo de 2017','A navigation and reservation based smart parking platform using genetic optimization for smart cities','Recibido'),
('Bischoff, J., & Nagel, K.','10 de diciembre de 2017','Integrating explicit parking search into a transport simulation','Recibido'),
('Fang, J., Ma, A., Fan, H., Cai, M., & Song, S.','20 de junio de 2018','Research on smart parking guidance and parking recommendation algorithm','Recibido'),
('Hakeem, A., Gehani, N., Ding, X., Curtmola, R., & Borcea, C. ','30 de julio de 2019','Multi-destination vehicular route planning with parking and traffic constraints','Recibido'),
('Hanzl, J.','10 de enero de 2020','Parking Information Guidance Systems and Smart Technologies Application Used in Urban Areas and Multi-storey Car Parks','Recibido'),
('Hedderich, M., Fastenrath, U., Isaac, G., & Bogenberger, K.','6 de unio de 2017','Adapting the A∗algorithm for park spot routing','Recibido'),
('Idri, A., Oukarfi, M., Boulmakoul, A., Zeitouni, K., & Masri, A.','13 de diciembre de 2017','A new time-dependent shortest path algorithm for multimodal transportation network','Recibido'),
('Jiang, L., Ai, W., & Li, J.','5 de abril de 2019','Intelligent Vehicle’s Control for Tracking Target Path.','Recibido'),
('Kanteti, D., Srikar, D. V. S., & Ramesh, T. K.','20 de abril de 2018','Intelligent smart parking algorithm','Recibido'),
('Kizilkaya, B., Caglar, M., Al-Turjman, F., & Ever, E.','7 de septiembre de 2018','An intelligent car park management system: Hierarchical placement algorithm based on nearest location','Recibido'),
('Kuhail, M. A., Boorlu, M., Padarthi, N., & Rottinghaus, C.','16 de agosto de 2019','Parking availability forecasting model','Recibido'),
('Lee, S.','12 de julio de 2013','Advances in Intelligent Systems and Computing: Preface','Recibido'),
('Li, W.','20 de septiembre de 2016','Notion of Control-Law Module and Modular Framework of Cooperative Transportation Using Multiple Nonholonomic Robotic Agents with Physical Rigid-Formation-Motion Constraints','Recibido'),
('Mannini, L., Cipriani, E., Crisalli, U., Gemma, A., & Vaccaro, G.','(15 de febrero de 2017','On-Street Parking Search Time Estimation Using FCD Data','Recibido'),
('Nakazato, T., & Namerikawa, T.','18 de marzo de 2019','Parking Lot Allocation Based on Matching Theory using Prediction-based Optimal Vehicle Routing','Recibido'),
('Nakrani, N., & Joshi, M.','18 de marzo de 2018','An Intelligent Fuzzy based Hybrid Approach for Parallel Parking in Dynamic Environment','Recibido'),
('Natarajan, A., Bharat, K., Kaustubh, G. R., Sai Praveen, P. N., Minal, M., Srinath, N. K., & Subramanya, K. N.','18 de abril de 2019','An approach to real time parking management using computer vision','Recibido'),
('Nie, Y., Xu, K., Chen, H., & Peng, L.','20 de abril de 2019','Crowd-parking: A New Idea of Parking Guidance Based on Crowdsourcing of Parking Location Information from Automobiles','Recibido'),
('Oh, K., Hong, S. K., & Kwon, O. K.','30 de mayo de 2015)',' Lifetime extension method for active matrix organic light-emitting diode displays using a modified stretched exponential decay model','Recibido'),
('Okoso, A., Otaki, K., & Nishi, T.','20 de enero de 2019','Multi-Agent Path Finding with Priority for Cooperative Automated Valet Parking','Recibido'),
('Parashar, S., & Kumar, G.','10 de julio de 2019','Smart parking system using genetic optimization a review','Recibido'),
('Peng, L., & Li, H.','18 de octurbre de 2016',' Searching parking spaces in urban environments based on non-stationary poisson process analysis','Recibido'),
('Qin, Y., Liu, F., & Wang, P.','3 de octubre de 2019','A feasible parking algorithm in form of path planning and following','Recibido'),
('Rehena, Z., Mondal, M. A., & Janssen, M.','0 de noviembre de 2018',' A multiple-criteria algorithm for smart parking: Making fair and preferred parking reservations in smart cities','Recibido'),
('Rehman, M. U., Shah, M. A., Khan, M., & Ahmad, S.','20 de marzo de 2018','A VANET based smart car parking system to minimize searching time, fuel consumption and CO2 emission','Recibido'),
('Shen, T., Hua, K., & Liu, J.','10 de noviembre de 2019','Optimized Public Parking Location Modelling for Green Intelligent Transportation System Using Genetic Algorithms','Recibido'),
('Singh, R., Dutta, C., Singhal, N., & Choudhury, T.','10 de mayo de 2020','An Improved Vehicle Parking Mechanism to reduce Parking Space Searching Time using Firefly Algorithm and Feed Forward Back Propagation Method','Recibido'),
('Sonny, A., Rai, P. K., Kumar, A., & Khan, M. Z. A.','14 de febrero 2020',' Deep Learning-Based Smart Parking Solution using Channel State Information in LTE-Based Cellular Networks','Recibido'),
('Sun, D. J., Ni, X. Y., & Zhang, L. H.','15 de junio de 2015','A discriminated release strategy for parking variable message sign display problem using agent-based simulation','Recibido'),
('Tang, J., Song, Y., Miller, H. J., & Zhou, X.','12 de enero de 2016','Estimating the most likely space-time paths, dwell times and path uncertainties from vehicle trajectory data: A time geographic method','Recibido'),
('Thomas, D., & Kovoor, B. C.','4 de diciembre de 2018','A Genetic Algorithm Approach to Autonomous Smart Vehicle Parking system','Recibido'),
('Wang, M., Dong, H., Li, X., Song, L., & Pang, D.','12 de junio de 2017','A Novel Parking System Designed for Smart Cities','Recibido'),
('Wang, X., Shi, H., & Zhang, C.','5 de marzo de 2020','Path Planning for Intelligent Parking System Based on Improved Ant Colony Optimization','Recibido'),
('Wu, Z., Jia, Q. S., & Guan, X.','30 de abril de 2016','Optimal Control of Multiroom HVAC System: An Event-Based Approach','Recibido'),
('Xiangdong, L., Yuefeng, C., Gang, C. E. N., & Zengwei, X.','19 de agosto de 2019','Prediction of short-term available parking space using LSTM model','Recibido'),
('Xie, L., Liu, J., Miao, C., & Liu, M.','13 de mayo de 2016','Study of Method on Parking Guidance Based on Video','Recibido'),
('Yongzhe, Z., Ma, B., & Wai, C. K.','14 de abril de 2018','A Practical Study of Time-Elastic-Band Planning Method for Driverless Vehicle for Auto-parking','Recibido'),
('Yujin, & Xiaoxue, G.','5 de junio de 2017','Optimal Route Planning of Parking Lot Based on Dijkstra Algorithm','Recibido'),
('Zajam, A., & Dholay, S.','4 de diciembre de 2018','Detecting Efficient Parking Space Using Smart Parking','Recibido'),
('Zeng, D., Zhou, Y., Yu, Z., Xiong, L., Xia, L., Zhang, P., Yao, J.','6 de noviembre de 2019','A Motion Planning Method Addressing Arbitrary Lots for Autonomous Parking Vehicle','Recibido'),
('Zhu, D.','28 de mayo de 2018','Deep learning over IoT big data-based ubiquitous parking guidance robot for parking near destination especially hospital','Recibido'),
('Zou, R., Wang, S., Wang, Z., Zhao, P., & Zhou, P.','23 de mayo de 2020','A Reverse Planning Method of Autonomous Parking Path','Recibido')



